src/Entity/Operation.php
<?php

namespace App\Entity;

use App\Repository\OperationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OperationRepository::class)
 */
class Operation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="operations")
     */
    private $User;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $Archiver;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getArchiver(): ?bool
    {
        return $this->Archiver;
    }

    public function setArchiver(?bool $Archiver): self
    {
        $this->Archiver = $Archiver;

        return $this;
    }
}

src/Controller/ProjetController.php
<?php

namespace App\Controller;

use DateTime;
use App\Entity\User;

use App\Entity\Operation;
use App\Form\OperationType;
use App\Repository\UserRepository;
use App\Repository\OperationRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\ChiffreAffaireRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ProjetController extends AbstractController
{
    /**
     * @Route("/", name="app_index")
     */
    public function index(UserRepository $repoUser, OperationRepository $repoOp,ChiffreAffaireRepository $repo): Response
    {
        $ca = $repo->find(1);
        $users = $repoUser->findAll();
        $operations = $repoOp->findAll();
        return $this->render('projet/index.html.twig', [
            'controller_name' => 'ProjetController',
            "users" => $users,
            "operations" => $operations,
            'Chiffre' => $ca
        ]);
    }

     /**
     * @Route("/profile/home", name="app_home")
     */
    public function home(OperationRepository $repo): Response
    {
        $Operations = $repo->findAll();
        return $this->render('projet/home.html.twig', [
            'controller_name' => 'ProjetController',
            'Operations' => $Operations,
            'id' => $this->getUser()
        ]);
    }

    /**
     * @Route("/superadmin/delete/{id}", name="app_delete", methods={"POST"})
     */
    public function delete(Request $request, User $user, UserRepository $userRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $user->getId(), $request->request->get('_token'))) {
            $userRepository->remove($user);
        }

        return $this->redirectToRoute('app_show_users', [], Response::HTTP_SEE_OTHER);
    }

     /**
     * @Route("/operation/create", name="app_createOp")
     */
    public function CreateOp(Request $request, EntityManagerInterface $manager,UserRepository $repo)
    {
        $Operation = new Operation;
        $form = $this->createForm(OperationType::class, $Operation);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $user = $repo->find($this->getUser());
            $Operation->setArchiver(true);
            $Operation->setUser($this->getUser());
            $user->setNbOperationEnCour(($user->getNbOperationEnCour()+1));
            $manager->persist($Operation,$user);
            $manager->flush();
            return $this->redirectToRoute("app_home");
        }
        return $this->render('projet/CreateOp.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/operation", name="app_operation")
     */
    public function listOperation(OperationRepository $repo): Response
    {
        $Operations = $repo->findAll();
        return $this->render('projet/listOperation.html.twig', [
            'controller_name' => 'ProjetController',
            'Operations' => $Operations,
            'id' => $this->getUser()
        ]);
    }

    /**
     * @Route("/operation/Terminer/{id}",  name="terminer_operation")
     */
    public function terminer(Operation $op, EntityManagerInterface $manager, UserRepository $repo,ChiffreAffaireRepository $repoA): Response
    {
        $ca = $repoA->find(1);
        if ($op->gettype() == "Petite") {
            $ca->setValeur($ca->getValeur() + 1000);
            $ca->setPetite($ca->getPetite() + 1000);
        }elseif($op->gettype() == "Moyenne"){
            $ca->setValeur($ca->getValeur() + 2500);
            $ca->setMoyenne($ca->getMoyenne() + 2500);
        }elseif ($op->gettype() == "Grosse") {
            $ca->setValeur($ca->getValeur() + 10000);
            $ca->setGrosse($ca->getGrosse() + 10000);
        }
        $ca->setDernierAjouts(DateTime::createFromFormat('d/m/Y à H:i',date('d/m/Y à H:i')));
        $user = $repo->find($this->getUser());
        $user->setNbOperationEnCour(($user->getNbOperationEnCour() - 1));
        $ca->setPourcentGrosse(($ca->getGrosse()*100)/$ca->getValeur());
        $ca->setPourcentMoyenne(($ca->getMoyenne()*100)/$ca->getValeur());
        $ca->setPourcentPetite(($ca->getPetite()*100)/$ca->getValeur());
        $op->setArchiver(false);
        $manager->persist($op,$ca);
        $manager->flush();
        return $this->redirectToRoute('app_home');
    }

    /**
     * @Route("/superadmin/ca", name="aff_ca")
     */
    public function AfficherCA(ChiffreAffaireRepository $repo,EntityManagerInterface $manager)
    {
        $ca = $repo->find(1);
        return $this->render('projet/AffChiAffaire.html.twig', [
            'Chiffre' => $ca
        ]);
    }
    
}

templates/projet/createOp.html.twig
{# {% extends 'base.html.twig' %}
{% block body %}
<style>

		</style>
	{{ form_start(form) }}
	{{ form_widget(form) }}
	<button type="submit" class="btn btn-success">Ajouter</button>
	{{ form_end(form) }}
{% endblock %} #}


{% extends 'base.html.twig' %}
{% block title %}Index
{% endblock %}
{% block body %}
 <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
	<style>
		html,
		body {
			min-height: 100%;
		}
		body,
		div,
		form,
		input,
		select,
		p {
			padding: 0;
			margin: 0;
			outline: none;
			font-family: Roboto, Arial, sans-serif;
			font-size: 16px;
			color: #eee;
		}
		body {
			background: url("https://www.hellomagazine.com/imagenes/homes/2019010866329/12-month-cleaning-calendar/0-312-637/cleaning-products-t.jpg") no-repeat center;
			background-size: cover;
		}
		h1,
		h2 {
			text-transform: uppercase;
			font-weight: 400;
		}
		h2 {
			margin: 0 0 0 8px;
		}
		.main-block {
			display: flex;
			flex-direction: column;
			justify-content: center;
			align-items: center;
			height: 100%;
			padding: 25px;
			background: rgba(0, 0, 0, 0.5);
		}
		.left-part,
		form {
			padding: 25px;
		}
		.left-part {
			text-align: center;
		}
		.fa-graduation-cap {
			font-size: 72px;
		}
		form {
			background: rgba(0, 0, 0, 0.4);
		}
		.title {
			display: flex;
			align-items: center;
			margin-bottom: 20px;
		}
		.info {
			display: flex;
			flex-direction: column;
		}
		input,
		select {
			padding: 5px;
			margin-bottom: 30px;
			background: transparent;
			border: none;
			border-bottom: 1px solid #eee;
		}
		input::placeholder {
			color: #eee;
		}
		option:focus {
			border: none;
		}
		option {
			background: black;
			border: none;
		}
		.checkbox input {
			margin: 0 10px 0 0;
			vertical-align: middle;
		}
		.checkbox a {
			color: #26A9E0;
		}
		.checkbox a:hover {
			color: #85D6DE;
		}
		.btn-item,
		button {
			padding: 10px 5px;
			margin-top: 20px;
			border-radius: 5px;
			border: none;
			background: #26A9E0;
			text-decoration: none;
			font-size: 15px;
			font-weight: 400;
			color: #fff;
		}
		.btn-item {
			display: inline-block;
			margin: 20px 5px 0;
		}
		button {
			width: 100%;
		}
		button:hover,
		.btn-item:hover {
			background: #85D6DE;
		}
		@media(min-width: 568px) {
			html,
			body {
				height: 100%;
			}
			.main-block {
				flex-direction: row;
				height: calc(100% - 50px);
			}
			.left-part,
			form {
				flex: 1;
				height: auto;
			}
		}
	</style>
</head>
<body>
	<div class="main-block">
		<div class="left-part">
			<h2>Projet Propar</h2>
			<div class="btn-group"></div>
		</div>
		{{form_start(form)}}
			<div class="title">
				<i class="fas fa-pencil-alt"></i>
				<h3>Nouvelle opération</h3>
			</div>
			<div class="info">

				{{form_widget(form.type)}}

				{{form_widget(form.description, {'attr': {'placeholder': 'Description','style' : 'width: 100%'}, "label":" "})}}

				{{ form_help(form.nom) }}

				{{form_widget(form.nom, {'attr': {'placeholder': 'Nom','style' : 'width: 100%'}, "label":" "})}}

				{{ form_help(form.prenom) }}

				{{form_row(form.prenom, {'attr': {'placeholder': 'Prénom','style' : 'width: 100%'}, "label":" "})}}

				{{form_row(form.adresse, {'attr': {'placeholder': 'Adresse','style' : 'width: 100%'}, "label":" "})}}
			</br>

			<button type="submit" class="btn btn-outline-success">
				Valider
			</button>
			
		</div>
	{{form_end(form)}}
</body></div></body></html>{% endblock %}

templates/projet/home.html.twig
 {% extends 'base.html.twig' %}
{% block title %}Page d'accueil
{% endblock %}
{% block body %}
    <h1 style="text-align:center">Bienvenue sur votre tableau de bord</h1>
    <h1 style="; margin-bottom: 0px; text-align: center; ">Opérations en cours</h1>
    <hr>
    <div style="display: flex; flex-wrap: wrap;">
        {% for Operation in Operations %}
            {% if app.user == Operation.User %}
                {% if Operation.Archiver  == true %}
                    <div style="margin-left: 30px; margin-right: 100px; margin-bottom: 30px; margin-top: 20px;">
                        <div class={% if Operation.type == "Grosse" %} "card text-white bg-danger mb-3" {% endif %} {% if Operation.type == "Moyenne" %} "card text-white bg-warning mb-3" {% endif %} {% if Operation.type == "Petite" %} "card text-white bg-info mb-3" {% endif %} style="max-width: 18rem;">
                            <div class="card-body">
                                <h5 class="card-title">{{ Operation.type }}
                                    opération</h5>
                                <p class="card-text">{{ Operation.description }}</p>
                                <p class="card-text">{{ Operation.nom }}
                                    {{ Operation.prenom }}</p>
                                <p class="card-text">{{ Operation.adresse }}</p>
                                <a href="{{ path("terminer_operation", {"id" : Operation.id}) }}" class="btn btn-primary">Terminer</a>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endif %}
        {% endfor %}
    </div><br>
    <h1 style="; margin-bottom: 0px; text-align: center; ">TERMINÉES</h1>
    <hr>
    <div style="display: flex; flex-wrap: wrap;">
        {% for Operation in Operations %}
            {% if app.user == Operation.User %}
                {% if Operation.Archiver  == false %}
                    <div style="margin-left: 30px; margin-right: 100px; margin-bottom: 30px; margin-top: 20px;">
                        <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
                            <div class="card-body">
                                <h5 class="card-title">{{ Operation.type }}
                                    opération</h5>
                                <p class="card-text">{{ Operation.description }}</p>
                                <p class="card-text">{{ Operation.nom }}
                                    {{ Operation.prenom }}</p>
                                <p class="card-text">{{ Operation.adresse }}</p>
                                <button type="button" class="btn btn-light" disabled>
                                    Terminer</button>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

templates/projet/index.html.twig
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Document</title>
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
		<script>
			function degres2radians(centreX, centreY, rayon, degres) {
var radians = (degres - 90) * Math.PI / 180.0;
return {
x: centreX + (rayon * Math.cos(radians)),
y: centreY + (rayon * Math.sin(radians))
};
}

function monArc(x, y, rayon, angleDepart, angleFin) {
var depart = degres2radians(x, y, rayon, angleFin);
var fin = degres2radians(x, y, rayon, angleDepart);
var arc180 = angleFin - angleDepart <= 180 ? "0" : "1";
var d = [
"M",
depart.x,
depart.y,
"A",
rayon,
rayon,
0,
arc180,
0,
fin.x,
fin.y,
"L",
x,
y,
"L",
depart.x,
depart.y
].join(" ");

return d;
}

function addElements(i) {
var svg = document.getElementsByTagName('svg')[0]; // Get le svg
angleDepart = angleDepart;
angleFin = (angleDepart + tabDonnees[i]);

// dessin des arcs de cercle
var path = document.createElementNS("http://www.w3.org/2000/svg", 'path'); // Create a path in SVG's namespace
path.setAttribute('fill', tabCouleur[i]);
path.setAttribute('d', monArc(120, 120, rayon, angleDepart * 3.6, angleFin * 3.6));
path.setAttribute('id', 'arc' + i);
path.setAttribute('p', i);
path.setAttribute('class', "arc");


// dessin des carres de legende
var rect = document.createElementNS("http://www.w3.org/2000/svg", 'rect'); // Create a path in SVG's namespace
rect.setAttribute('width', '16');
rect.setAttribute('height', '16');
rect.setAttribute('x', 260);
rect.setAttribute('y', 30 * i + 70);
rect.setAttribute('fill', tabCouleur[i]);
rect.setAttribute('id', 'rect' + i);

// dessin des textes de legende
var text = document.createElementNS('http://www.w3.org/2000/svg', 'text');
text.setAttribute('x', 280);
text.setAttribute('y', 30 * i + 70 + 12);
text.setAttribute('fill', '#999');
text.setAttribute('font-size', '12');
text.setAttribute('font-family', 'sans-serif');
text.setAttribute('font-weight', 'normal');
text.setAttribute('id', 'text' + i);
text.textContent = tabLabel[i]+' ('+tabDonnees[i]+'%)';

// ajout des elements au svg
svg.appendChild(path);
svg.appendChild(rect);
svg.appendChild(text);
var el = document.getElementById('arc' + i);
el.addEventListener("click", clickArc, false);
}
let total = {{ Chiffre.pourcentGrosse }} + {{ Chiffre.pourcentMoyenne }} + {{ Chiffre.pourcentPetite }};
let restant = 100 - total;
function drawGraphCam() {
angleDepart = 0;
angleFin = 0;
rayon = 100;
tabLabel = ["Grosse", "Moyenne", "Petite"];

tabDonnees = [
{{ Chiffre.pourcentGrosse }},
{{ Chiffre.pourcentMoyenne }},
{{ Chiffre.pourcentPetite }}
];
tabCouleur = ["red", "orange", "rgb(0, 195, 255)"];
cible = 'a';
// creation du SVG
document.getElementById(cible).innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width=500 height=300></svg>';
// pour chaque entree des tableaux on dessine les arc , carres et textes
for (i = 0; i < tabDonnees.length; i ++) {
addElements(i);
angleDepart = angleFin;
}
}
var clickArc = function () {
alert(tabLabel[this.getAttribute("p")] + " : " + tabDonnees[this.getAttribute("p")] + "%");
}
		</script>
	</head>
	<body onload="drawGraphCam()">
		<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
			<div class="container-fluid">
				<a class="navbar-brand" href="/">Projet Propar</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
					<div class="navbar-nav ">

						{% if app.user %}
							<a class="nav-link" href="/operation">Mes opérations</a>
						{% endif %}


						{% if app.user %}
							{% if app.user.NbOperationAutoriser > app.user.NbOperationEnCour %}
								<a class="nav-link" href="/operation/create">Ajout opération</a>
							{% endif %}
							{% if app.user.NbOperationAutoriser <= app.user.NbOperationEnCour %}
								<a class="nav-link disabled" href="/operation/create">Ajout opération</a>
							{% endif %}
						{% endif %}


						{% if is_granted("ROLE_SUPER_ADMIN") %}
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
									Gestion d'utilisateurs
								</a>
								<ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
									<li>
										<a class="dropdown-item" href="/superadmin/show">Voir les utilisateurs</a>
									</li>
									<li>
										<a class="dropdown-item" href="/superadmin/registration">Nouvel utilisateur</a>
									</li>
								</ul>
							</li>

						{% endif %}
						{% if not app.user %}
							<a class="nav-link position-absolute" href="/login" style="border : solid 1px ;border-radius:5px ;right: 10px; top: 5px;">Connexion</a>
						{% else %}
							<a class="nav-link position-absolute" href="/logout" style="border : solid 1px ;border-radius:5px;right: 10px; top: 5px">Déconnexion</a>
						{% endif %}
					</div>
				</div>
			</div>
		</nav>
		{% if is_granted("ROLE_SUPER_ADMIN") %}
			<hr class="mt-5 mb-5">
			<h2 style="text-align:center;">Chiffre d'affaire</h2>
			<hr class="mt-5 mb-5">
			<div class="container px-3 py-3" id="featured-3">

				<div style="display:flex;">
					<div id='a'></div>
					<div style="display:flex; flex-direction: column; justify-content: center; padding-right: 15px; ">
						<h1>{{ Chiffre.valeur }}€</h1>
					</div>

					<div style="display:flex; flex-direction: column; justify-content: center; border-left: 2px solid rgb(190, 190, 190); padding-left: 15px;">
						<h1>Par type:
						</h1>
						<h5>&nbsp;&nbsp;&nbsp;Grosse:&nbsp;
							{{ Chiffre.Grosse }}€</h5>
						<h5>&nbsp;&nbsp;&nbsp;Moyenne:&nbsp;{{ Chiffre.Moyenne }}€</h5>
						<h5>&nbsp;&nbsp;&nbsp;Petite:&nbsp;{{ Chiffre.Petite }}€</h5>
					</div>
				{% endif %}

				<br>

			</div>

		</div>
		<hr class="mt-5 mb-5">
		<h2 style="text-align:center;">Liste des opérations en cours</h2>
		<hr class="mt-5 mb-5">

		<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/jqc-1.12.4/dt-1.11.5/datatables.min.css"/>

		<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/jqc-1.12.4/dt-1.11.5/datatables.min.js"></script>

		<div class="container px-3 py-3" id="featured-3">
			<table id="datatable" class="table table-striped table-bordered table-hover" style="width:100%">
				<thead>
					<tr>
						<th class="th-sm">Opération
						</th>
						<th class="th-sm">Description
						</th>
						<th class="th-sm">Client
						</th>
						<th class="th-sm">Employé
						</th>
						<th class="th-sm">Role
						</th>
						<th class="th-sm">Terminée ?
						</th>
						<th class="th-sm">Détail
						</th>
					</tr>
				</thead>
				<tbody>

					<tr>
						{% for operation in operations %}
							<td class={% if operation.type == "Grosse" %} "table-danger" {% endif %} {% if operation.type == "Moyenne" %} "table-warning" {% endif %} {% if operation.type == "Petite" %} "table-primary" {% endif %}>{{ operation.type }}</td>


							<td>{{ operation.description }}</td>
							<td>{{ operation.nom }}
								{{ operation.prenom }}</td>
							<td>{{ operation.getUser().nom }}
								{{ operation.getUser().prenom }}</td>
							<td>
								{% if 'ROLE_SUPER_ADMIN' in operation.getUser().getroles(TRUE)  %}
									<p>Expert</p>
								{% endif %}

								{% if 'ROLE_ADMIN' in operation.getUser().getroles(TRUE)  %}
									<p>Senior</p>
								{% endif %}

								{% if 'ROLE_USER' in operation.getUser().getroles(TRUE)  %}
									<p>Apprenti</p>
								{% endif %}
							</td>

							{% if operation.archiver  %}
								<td>Non</td>
							{% else %}
								<td class="table-dark">Oui</td>
							{% endif %}


							<td>


								{# INSERER BOUTON DETAIL ICI #}


							</td>
						</tr>

					{% endfor %}

				</tbody>
				<tfoot>
					<tr>
						<th class="th-sm">Opération
						</th>
						<th class="th-sm">Description
						</th>
						<th class="th-sm">Client
						</th>
						<th class="th-sm">Employé
						</th>
						<th class="th-sm">Role
						</th>
						<th class="th-sm">Terminée ?
						</th>
						<th class="th-sm">Détail
						</th>
					</tr>
				</tfoot>

			</tbody>
		</body>
	</body>
</html></table></div><script type="text/javascript">$(document).ready(function () {
$('#datatable').DataTable();
});</script></body></html>

templates/projet/listOperation.html.twig
{% extends 'base.html.twig' %}
{% block title %}Page d'accueil
{% endblock %}
{% block body %}
    <h1 style="text-align:center">Bienvenue sur votre tableau de bord</h1>
    <h1 style="; margin-bottom: 0px; text-align: center; ">Opérations en cours</h1>
    <hr>
    <div style="display: flex; flex-wrap: wrap;">
        {% for Operation in Operations %}
            {% if app.user == Operation.User %}
                {% if Operation.Archiver  == true %}
                    <div style="margin-left: 30px; margin-right: 100px; margin-bottom: 30px; margin-top: 20px;">
                        <div class={% if Operation.type == "Grosse" %} "card text-white bg-danger mb-3" {% endif %} {% if Operation.type == "Moyenne" %} "card text-white bg-warning mb-3" {% endif %} {% if Operation.type == "Petite" %} "card text-white bg-info mb-3" {% endif %} style="max-width: 18rem;">
                            <div class="card-body">
                                <h5 class="card-title">{{ Operation.type }}
                                    opération</h5>
                                <p class="card-text">{{ Operation.description }}</p>
                                <p class="card-text">{{ Operation.nom }}
                                    {{ Operation.prenom }}</p>
                                <p class="card-text">{{ Operation.adresse }}</p>
                                <a href="{{ path("terminer_operation", {"id" : Operation.id}) }}" class="btn btn-primary">Terminer</a>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endif %}
        {% endfor %}
    </div><br>
    <h1 style="; margin-bottom: 0px; text-align: center; ">TERMINÉES</h1>
    <hr>
    <div style="display: flex; flex-wrap: wrap;">
        {% for Operation in Operations %}
            {% if app.user == Operation.User %}
                {% if Operation.Archiver  == false %}
                    <div style="margin-left: 30px; margin-right: 100px; margin-bottom: 30px; margin-top: 20px;">
                        <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
                            <div class="card-body">
                                <h5 class="card-title">{{ Operation.type }}
                                    opération</h5>
                                <p class="card-text">{{ Operation.description }}</p>
                                <p class="card-text">{{ Operation.nom }}
                                    {{ Operation.prenom }}</p>
                                <p class="card-text">{{ Operation.adresse }}</p>
                                <button type="button" class="btn btn-light" disabled>
                                    Terminer</button>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}