src/Entity/Operation.php
<?php

namespace App\Entity;

use App\Repository\OperationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OperationRepository::class)
 */
class Operation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="operations")
     */
    private $User;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $Archiver;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getArchiver(): ?bool
    {
        return $this->Archiver;
    }

    public function setArchiver(?bool $Archiver): self
    {
        $this->Archiver = $Archiver;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>
			{% block title %}Welcome!
			{% endblock %}
		</title>
		{# Run `composer require symfony/webpack-encore-bundle`
								           and uncomment the following Encore helpers to start using Symfony UX #}
		{% block stylesheets %}
			{# {{ encore_entry_link_tags('app') }} #}
		{% endblock %}

		{% block javascripts %}
			{# {{ encore_entry_script_tags('app') }} #}
		{% endblock %}

		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
		
		{% block head %}{% endblock %}
	</head>
	<body>
		<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
			<div class="container-fluid">
				<a class="navbar-brand" href="/" >Projet Propar</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
					<div class="navbar-nav ">
						
						{% if app.user %}
							<a class="nav-link" href="/operation">Mes opérations</a>
						{% endif %}


						{% if app.user %}
							{% if app.user.NbOperationAutoriser > app.user.NbOperationEnCour %}
                                <a class="nav-link" href="/operation/create">Ajout opération</a>
                            {% endif %}
                            {% if app.user.NbOperationAutoriser <= app.user.NbOperationEnCour %}
								        <a class="nav-link disabled" href="/operation/create">Ajout opération</a>
                            {% endif %}
						{% endif %}


						{% if is_granted("ROLE_SUPER_ADMIN") %}
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
									Gestion d'utilisateurs
								</a>
								<ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
									<li>
										<a class="dropdown-item" href="/superadmin/show">Voir les utilisateurs</a>
									</li>
									<li>
										<a class="dropdown-item" href="/superadmin/registration">Nouvel utilisateur</a>
									</li>
								</ul>
							</li>
						{% endif %}
						{% if not app.user %}
							<a class="nav-link position-absolute"  href="/login" style="border : solid 1px ;border-radius:5px ;right: 10px; top: 5px">Connexion</a>
						{% else %}
							<a class="nav-link position-absolute" href="/logout" style="border : solid 1px ;border-radius:5px;right: 10px; top: 5px">Déconnexion</a>
						{% endif %}

					</div>
				</div>
			</div>
		</nav>
		{% block body %}{% endblock %}
	</body>
</html>